### ISSUE TITLE
Can i give input images of my own wish without the images in training dataset?

### ISSUE THREAD

**Issue by Naveennavik** [akanimax/msg-stylegan-tf#1]
To test the model can i give the input my images which are not in the train dataset will that work?

**Comment by akanimax** [comment]
@Naveennavik,

MSG-GAN is still a GAN :smile:. In order to be able to do what you are asking, I'd suggest you look into VAEs and/or Flow based models.

Hope this helps.

Cheers :beers:!
@akanimax
