### ISSUE TITLE
How to resume training from prior pkl file?

### ISSUE THREAD

**Issue by paulklee-germany** [akanimax/msg-stylegan-tf#2]
Hello, I tried to resume my training from the previous learning, but cannot make it. Please can you give me a brief guide? Thank you! :)

**Comment by Pulse9-dev** [comment]
Oh, I found a solution. I can specify pkl file on training_loop.py!

**Comment by akanimax** [comment]
@paulklee-germany,

Ah, this is unfortunately not supported currently and I am sorry, but I wouldn't have the time to include this feature anytime soon. Please feel free to submit a PR if you add this feature to the code. 

Sorry couldn't help further :frowning:. 

Cheers :beers:!
@akanimax
