### ISSUE TITLE
Not able to run code on CPU. 

### ISSUE THREAD

**Issue by naklecha** [akanimax/msg-stylegan-tf#3]
I want to use the pre-trained model but I am not able to do so using CPU. I don't have a GPU and its raising error.

**Comment by akanimax** [comment]
@Naklecha,

I believe you can run inference on a cpu for a a small resolution synthesis query. Please check this out -> https://discuss.pytorch.org/t/on-a-cpu-device-how-to-load-checkpoint-saved-on-gpu-device/349.

I hope this helps. 
Please feel free to reopen / write post closure comments if you have any more questions.

Cheers :beers:!
@akanimax
