### ISSUE TITLE
Architectural explanation

### ISSUE THREAD

**Issue by mrclasalvia** [akanimax/msg-stylegan-tf#4]
Dear all,
I would like to kindly ask further explanation about the architectural design of the network, for instance:
- Why are there multiple skip connections and how the whole thing is trained? 
- Do I have to concatenate both the multi-scale layers from the generator and random real images instances while evaluating the discriminator? How do I do that?
- There's a "combinational layer" in yellow, what's that?
I have indeed read the original paper but still, there are some things that I cannot understand so I hope you will kindly answer me.

Looking forward to hearing from you soon.

Sincerely

**Comment by akanimax** [comment]
Hey @mrclasalvia, 

I am sorry for the late reply. It is becoming more and more difficult for me to find time for community work :wink:.
I am not sure, if you still have these questions. But please feel free to write us (Oliver and/or I) an email if you still have these questions. I'd be happy to help.

Cheers :beers:!
@akanimax
