### ISSUE TITLE
dj contains which part?aj  contains which part? 

### ISSUE THREAD

**Issue by jiaying96** [akanimax/msg-stylegan-tf#5]
![image](https://user-images.githubusercontent.com/16167043/78979231-02088600-7b4e-11ea-82c0-e113f76f694b.png)
![image](https://user-images.githubusercontent.com/16167043/78979269-16e51980-7b4e-11ea-8f39-a735cf1c817c.png)

**Comment by akanimax** [comment]
@jiaying96, 

![image](https://user-images.githubusercontent.com/16590868/78981372-1766bb80-7b20-11ea-8030-e47dd506bd8d.png)
The `dj` consists of the three layers after combine layer in every function block. (see diagram).

What you are pointing to is the output `o_i` coming from the generator (or downsampled real images).

Hope this helps!

Best regards,
@akanimax

**Comment by akanimax** [comment]
Please feel free to reopen if you have any more questions... :smile: :+1:!

**Comment by jiaying96** [comment]
![image](https://user-images.githubusercontent.com/16167043/78983915-b8249d80-7b57-11ea-8f52-fbb969e61a99.png)
why input is real image or synthesized image？not like discriminator in GAN, input are  real image and synthesized image
