### ISSUE TITLE
why input is real image or synthesized image？not like discriminator in GAN, input are real image and synthesized image

### ISSUE THREAD

**Issue by jiaying96** [akanimax/msg-stylegan-tf#6]
![image](https://user-images.githubusercontent.com/16167043/78984479-e787da00-7b58-11ea-969c-16200d39ba04.png)

**Comment by akanimax** [comment]
@jiaying96,

The input to the discriminator `thought of as a mathematical function`, is either the true samples or the generated fake samples. We mention that in the paper for explicitness. 
Hope this helps!

Cheers :beers:!
@akanimax
