### ISSUE TITLE
Would you provide a pytorch version code？

### ISSUE THREAD

**Issue by Johnson-yue** [akanimax/msg-stylegan-tf#7]
Hi， I am using your MSG-GAN code ， and it very human-readable and good for user
I tried to read the msg-stylegan but， tensorflow version is so difficult to read ，maybe it's efficient？？

If you have proved the effectiveness of the method, I wonder if it is convenient to provide pytorch version of the code for more people to use

Thank you

**Comment by akanimax** [comment]
@Johnson-yue,

Yeah you are right. The method is published now and I think it is a good idea to port this code in PyTorch. 
Unfortunately I am extremely busy these days. But please feel free to take this up if you'd like. 

Cheers :beers:!
@akanimax
