### ISSUE TITLE
WGAN-GP loss implementation

### ISSUE THREAD

**Issue by TharunMohandoss** [akanimax/msg-stylegan-tf#8]
Hi,
    Thanks for creating this repository! I'm implementing the MSG-GAN method for my own project and I'm trying to use WGAN-GP loss, but I'm finding it difficult since there are multiple images. Could you point to the WGAN-GP loss implementation with multiple images in this repo so that I can use it for reference?
Thanks,
Tharun Mohandoss

**Comment by akanimax** [comment]
@TharunMohandoss,

Sorry for the late reply. You could look for the loss implementations here -> https://github.com/akanimax/msg-stylegan-tf/blob/master/training/loss.py#L22. What do you mean by loss implementation with multiple images?

@akanimax
